import pathlib
from gen_utils import *
from dk2cxx import *


def format_struct_cpp(
    struct: sgmap.Struct,
    vtable_map: dict[str, sgmap.Global]):
  yield format_id_line(struct.id)

  def format_cpp_head():
    yield format_middle(f"warning: file is generated by {pathlib.Path(__file__).name}")
    yield f"#include <{build_struct_path(struct, 'h')}>"
    yield f"#include <dk2_globals.h>"
    yield empty_line
    yield f"using namespace dk2;"
    yield empty_line
    yield f"#define relink_stub(name) printf(\"[fatal]: stub \"#name\" call\\n\"); ::abort();"
    yield empty_line
  yield from map(format_autogen_line, format_cpp_head())

  def format_cpp_body():
    yield f"#pragma optimize( \"\", off )"
    if struct.vtable is not None:
      yield f"// virtual functions"
      offs = struct.vtable.calc_fields_offs()
      for field in struct.vtable.fields:
        assert field.type.kind == sgmap.TypeKind.Ptr
        ptr_t = field.type  # type: sgmap.PtrType
        assert ptr_t.type.kind == sgmap.TypeKind.Function
        fun_t = ptr_t.type  # type: sgmap.FunctionType
        name = field.name
        if '::' in name:
          name = name[name.index('::') + 2:]
        name = f"v_{name}"

        suffix = "  // assembly" if fun_t.declspec is sgmap.Declspec.Assembly else ''
        name = f"{struct.name}::{format_function_name(name)}"
        ret = f" relink_stub({name}); "
        yield f"/*{offs:-3X}*/ {format_function(fun_t, name)} {{{ret}}}{suffix}"
        offs += field.type.get_size()
      yield empty_line
      vtable_glob = vtable_map.get(struct.vtable.id, None)
      if vtable_glob is not None:
        yield f"/*{vtable_glob.va:08X}*/ void **{struct.name}::vftable() {{ return dk2::{vtable_glob.name}; }}"
    if struct.functions:
      yield f"// member functions"
      for glob in struct.functions:
        fun_t = glob.type  # type: sgmap.FunctionType
        name = glob.name
        name = name.replace('::', '_')
        if name.startswith(f"{struct.name}_"):
          name = name[len(struct.name) + 1:]
        name = format_function_name(name)

        suffix = "  // assembly" if fun_t.declspec is sgmap.Declspec.Assembly else ''
        name = f"{struct.name}::{name}"
        ret = f" relink_stub({name}); "
        yield f"/*{glob.va:08X}*/ {format_function(fun_t, name)} {{{ret}}}{suffix}"
      yield empty_line
    yield f"#pragma optimize( \"\", on )"
  yield from map(format_autogen_line, format_cpp_body())
