import pathlib
from gen_utils import *
from dk2cxx import *


def format_globals_h(globals: list[sgmap.Global]):
  define_name = f"DK2_GLOBALS_H"

  def format_h_head():
    yield format_middle(f"warning: file is generated by {pathlib.Path(__file__).name}")
    yield empty_line
    yield f"#ifndef {define_name}"
    yield f"#define {define_name}"
    yield empty_line
    yield f"#include <cstdint>"
    yield f"#include <cstdio>"
    yield f"#include <dinput.h>"
    yield f"#include <ddraw.h>"
    yield f"#include <d3d.h>"
    yield f"#include <xmmintrin.h>"
    yield empty_line
    complete_types = set()
    ref_types = set()
    for glob in filter(filter_global_var, globals):
      if is_vtable(glob):
        continue
      collect_types(glob.type, complete_types, ref_types, False)
    for complete_struct in sorted(complete_types, key=lambda s: s.name):
      yield f"#include <{build_struct_path(complete_struct, 'h')}>"
      if complete_struct.name in ref_types:
        ref_types.remove(complete_struct.name)
    if ref_types:
      yield empty_line
      yield f"namespace dk2 {{"
      for name in sorted(ref_types):
        yield f"  struct {name};"
      yield f"}}  // namespace dk2"
    yield empty_line
  yield from map(format_autogen_line, format_h_head())

  def format_h_body():
    yield f"namespace dk2 {{"
    for glob in filter(filter_global_var, globals):
      glob_type = glob.type
      if is_vtable(glob):
        stru_t = glob.type  # type: sgmap.StructType
        glob_type = sgmap.ArrayType(sgmap.PtrType(sgmap.VoidType()), stru_t.struct.size // 4)
      name = glob.name.replace('::', '_')
      if name.startswith('??_R'):
        continue
      if name.startswith('__CT??_R'):
        continue
      if name.startswith('__CTA2?A'):
        continue
      if name.startswith('__CTA3?A'):
        continue
      if name.endswith('_vftable'):
        continue
      # if glob_type.kind is sgmap.TypeKind.Array:
      #   name = f"(&{name})"
      # else:
      #   name = f"&{name}"
      yield f"/*{glob.va:08X}*/ extern {format_type(glob_type, name)};"
    yield f"}}  // namespace dk2"
  yield from map(format_autogen_line, format_h_body())

  def format_h_tail():
    yield f"#endif //{define_name}"
    yield empty_line
  yield from map(format_autogen_line, format_h_tail())
