import pathlib
from gen_utils import *
from dk2cxx import *


def format_functions_cpp(globals: list[sgmap.Global]):
  def format_cpp_head():
    yield format_middle(f"warning: file is generated by {pathlib.Path(__file__).name}")
    yield f"#include <dk2_functions.h>"
    yield empty_line
    yield f"using namespace dk2;"
    yield empty_line
    yield f"#define relink_stub(name) printf(\"[fatal]: stub \"#name\" call\\n\"); ::abort();"
    yield empty_line
  yield from map(format_autogen_line, format_cpp_head())

  def format_cpp_body():
    yield f"#pragma optimize( \"\", off )"
    for glob in filter(filter_function_var, globals):
      fun_t = glob.type  # type: sgmap.FunctionType
      suffix = "  // assembly" if fun_t.declspec is sgmap.Declspec.Assembly else ''
      # ret = ''
      # if fun_t.ret.kind is sgmap.TypeKind.Ptr:
      #   ret = ' return NULL; '
      # elif fun_t.ret.kind is sgmap.TypeKind.Bool:
      #   ret = ' return false; '
      # elif fun_t.ret.kind in [
      #   sgmap.TypeKind.Int, sgmap.TypeKind.Float,
      #   sgmap.TypeKind.Winapi
      # ]:
      #   ret = ' return 0; '
      name = f"dk2::{format_function_name(glob.name)}"
      ret = f" relink_stub({name}); "
      yield f"/*{glob.va:08X}*/ {format_function(fun_t, name)} {{{ret}}}{suffix}"
    yield empty_line
    yield f"#pragma optimize( \"\", on )"
  yield from map(format_autogen_line, format_cpp_body())

